//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAPT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CouncilDecision
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CouncilDecision()
        {
            this.InPrincipal_Council = new HashSet<InPrincipal_Council>();
        }
    
        public int Id { get; set; }
        public bool Selection { get; set; }
        public string SignedBy { get; set; }
        public Nullable<System.DateTime> SignedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InPrincipal_Council> InPrincipal_Council { get; set; }
    }
}
