//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAPT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EndorsementCollab
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EndorsementCollab()
        {
            this.ExternalReview_Endorsement = new HashSet<ExternalReview_Endorsement>();
        }
    
        public int Id { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<bool> Selection { get; set; }
        public string HeldDate { get; set; }
        public string SignedBy { get; set; }
        public Nullable<System.DateTime> SignedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExternalReview_Endorsement> ExternalReview_Endorsement { get; set; }
        public virtual Ref_Department Ref_Department { get; set; }
    }
}
