//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAPT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class General
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public General()
        {
            this.Department_General = new HashSet<Department_General>();
            this.Proposals = new HashSet<Proposal>();
            this.Proposer_General = new HashSet<Proposer_General>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string AreasStudy { get; set; }
        public Nullable<int> LevelId { get; set; }
        public Nullable<int> FacultyId { get; set; }
        public Nullable<int> DeliveryId { get; set; }
        public string FirstDateIntake { get; set; }
        public Nullable<int> ExpectedStudents { get; set; }
        public Nullable<int> MaxStudents { get; set; }
        public string CappingReason { get; set; }
        public Nullable<int> DurationSemesters { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Department_General> Department_General { get; set; }
        public virtual Ref_Level Ref_Level { get; set; }
        public virtual Ref_Faculty Ref_Faculty { get; set; }
        public virtual Ref_Delivery Ref_Delivery { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Proposal> Proposals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Proposer_General> Proposer_General { get; set; }
    }
}
