//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAPT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InPrincipal_Senate
    {
        public int Id { get; set; }
        public int InPrincipalId { get; set; }
        public int SenateDecisionId { get; set; }
    
        public virtual InPrincipal InPrincipal { get; set; }
        public virtual SenateDecision SenateDecision { get; set; }
    }
}
