//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAPT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgrammeRationale
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProgrammeRationale()
        {
            this.Proposals = new HashSet<Proposal>();
        }
    
        public int Id { get; set; }
        public Nullable<int> RationaleId { get; set; }
        public Nullable<int> DemandId { get; set; }
        public Nullable<int> PsId { get; set; }
        public Nullable<int> TentativePsId { get; set; }
    
        public virtual Demand Demand { get; set; }
        public virtual ProgrammeOfStudy ProgrammeOfStudy { get; set; }
        public virtual Rationale Rationale { get; set; }
        public virtual TentativeP TentativeP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Proposal> Proposals { get; set; }
    }
}
