//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAPT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecommendationFic
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RecommendationFic()
        {
            this.Approval_Recommendation = new HashSet<Approval_Recommendation>();
        }
    
        public int Id { get; set; }
        public Nullable<int> FacultyId { get; set; }
        public Nullable<bool> Selection { get; set; }
        public string HeldDateA { get; set; }
        public string HeldDateB { get; set; }
        public string SignedBy { get; set; }
        public Nullable<System.DateTime> SignedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Approval_Recommendation> Approval_Recommendation { get; set; }
        public virtual Ref_Faculty Ref_Faculty { get; set; }
    }
}
