//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAPT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatementServ
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StatementServ()
        {
            this.Approval_Statement = new HashSet<Approval_Statement>();
        }
    
        public int Id { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<bool> Selection { get; set; }
        public string Reservations { get; set; }
        public string SignedBy { get; set; }
        public Nullable<System.DateTime> SignedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Approval_Statement> Approval_Statement { get; set; }
        public virtual Ref_Department Ref_Department { get; set; }
    }
}
