//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAPT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Year_Unit
    {
        public int Id { get; set; }
        public int YearId { get; set; }
        public int UnitId { get; set; }
        public Nullable<int> Period { get; set; }
        public Nullable<int> Coe { get; set; }
        public Nullable<int> Ects { get; set; }
        public string Lecturer { get; set; }
        public Nullable<int> Compensating { get; set; }
        public string CompensatingReason { get; set; }
    
        public virtual Ref_Unit Ref_Unit { get; set; }
        public virtual Year Year { get; set; }
    }
}
