//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAPT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Year
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Year()
        {
            this.Year_Unit = new HashSet<Year_Unit>();
        }
    
        public int Id { get; set; }
        public Nullable<int> TotalEcts { get; set; }
        public Nullable<int> TentativePsId { get; set; }
        public Nullable<int> YearNo { get; set; }
    
        public virtual TentativeP TentativeP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Year_Unit> Year_Unit { get; set; }
    }
}
